blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/fsMHMhAHRV
    about: Ask questions and chat with the community on Discord.
  - name: ðŸ“– Documentation
    url: https://github.com/DevVentures/DeckShala/wiki
    about: Browse the project documentation.
